# Matugen Dynamic Colors for Kitty
foreground            #f1dfd9
background            #1a110e
selection_foreground  #552008
selection_background  #ffb599
cursor                #ffb599
cursor_text_color     #552008
url_color             #d4c78e

# Window border
active_border_color   #ffb599
inactive_border_color #a08d86

# Tab bar
active_tab_foreground   #552008
active_tab_background   #ffb599
inactive_tab_foreground #d8c2bb
inactive_tab_background #271e1a

# Normal Colors
color0  #140c09
color1  #BF616A
color2  #A3BE8C
color3  #d4c78e
color4  #ffb599
color5  #e7beaf
color6  #71361d
color7  #f1dfd9

# Bright Colors
color8  #a08d86
color9  #BF616A
color10 #A3BE8C
color11 #4f471a
color12 #ffb599
color13 #5d4035
color14 #71361d
color15 #d8c2bb
