# Matugen Dynamic Colors for Kitty
foreground            #FAFCFB
background            #000000
selection_foreground  #FAFCFB
selection_background  #584e51
cursor                #b59790
cursor_text_color     #000000
url_color             #a5a0b6

# Window border
active_border_color   #d6d3de
inactive_border_color #584e51

# Tab bar
active_tab_foreground   #000000
active_tab_background   #a5a0b6
inactive_tab_foreground #cfd3cd
inactive_tab_background #141214

# Normal Colors
color0  #070607
color1  #c38b7b
color2  #87a9b0
color3  #6B5E73
color4  #b59790
color5  #c4d8e2
color6  #a5a0b6
color7  #cfd3cd

# Bright Colors
color8  #584e51
color9  #c38b7b
color10 #87a9b0
color11 #6B5E73
color12 #b59790
color13 #c4d8e2
color14 #a5a0b6
color15 #e2dddc
