# Matugen Generated Hyprland Color Variables
$primary = rgba(ffb599ee)
$primary_container = rgba(71361dee)
$tertiary = rgba(d4c78eee)
$secondary = rgba(e7beafee)
$surface = rgba(1a110eee)
$surface_container = rgba(271e1aee)
$outline = rgba(a08d86aa)
$inactive_border = rgba(3d322faa)
$active_border = rgba(ffb599ee) rgba(d4c78eee) 45deg
