# Matugen Generated Hyprland Color Variables
$primary = rgba(b59790ee)
$primary_container = rgba(584e51ee)
$tertiary = rgba(e2dddcee)
$secondary = rgba(a5a0b6ee)
$surface = rgba(000000ee)
$surface_container = rgba(141214ee)
$outline = rgba(584e51aa)
$inactive_border = rgba(584e51aa)
$active_border = rgba(8a8588ee) rgba(e2dddcee) 45deg
